controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

app_quiz:
    path: /quiz
    controller: App\Controller\QuizController::showQuizForm